### PR TITLE
[12.0][IMP] Fields for NF-e of SN

### PR DESCRIPTION
**Pull request by ygcarvalh**
Good afternoon people.

The PR adds the necessary fields for the generation of the NF-e for the different CST codes for te Simples Nacional. It also changes the monetary values for float.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@ygcarvalh pode fazer um rebase por favor ?

**Comment by ygcarvalh** [comment]
This PR depends on https://github.com/OCA/l10n-brazil/pull/1270 for the creation of the new Simples Nacional variables that are generated for the fields of the NF-e.

**Comment by mileo** [comment]
Favor fechar este PR e propor direto para 12.0 da OCA.

**Comment by ygcarvalh** [comment]
Este PR foi transferido para: https://github.com/OCA/l10n-brazil/pull/1275

**Pull request closed without merging**
